[package]
name = "gallery_of_babel"
version = "0.1.0"
authors = ["FredericaBernkastel <bernkastel.frederica@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
image = { version = "0.23.12", default_features = false, features = ["png"] }
plotters = { version = "^0.3.0", default_features = false, features = ["bitmap_backend", "bitmap_encoder"] }
rand = "0.8.2"
rand_pcg = "0.3.0"
rayon = "1.5.0"
open = "1.4.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1