[package]
name = "gallery_of_babel"
version = "0.1.0"
authors = ["FredericaBernkastel <bernkastel.frederica@protonmail.com>"]
edition = "2018"

[lib]
name = "lib"
path = "src/lib/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
error-chain = "0.12.4"
image = { version = "0.23.12", default_features = false, features = ["png", "jpeg"] }
plotters = { version = "^0.3.0", default_features = false, features = ["bitmap_backend", "bitmap_encoder"] }
rand = "0.8.2"
rand_pcg = "0.3.0"
rayon = "1.5.0"
open = "1.4.0"
float-cmp = "0.8.0"
walkdir = "2.3.1"
lexical-sort = "0.3.1"
exr = "1.0.0"
ocl = "0.19.3"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
debug = true # full debug symbols